# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-12 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0002_remove_message_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(max_length=500)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
