# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-14 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0003_newsurls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsurls',
            old_name='create',
            new_name='created_at',
        ),
    ]
