# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-16 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_app', '0004_auto_20190214_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsurls',
            name='site_url',
            field=models.CharField(default='https://nversia.ru', max_length=50),
            preserve_default=False,
        ),
    ]
